q1-1: q1-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q1-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q2-1: q2-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q2-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q3-1: q3-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q3-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q4-1: q4-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q4-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q5-1: q5-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q5-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q6-1: q6-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q6-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q7-1: q7-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q7-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

q8-1: q8-1.cpp
	# build and execute
	g++ -O2 -std=c++17 q8-1.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out

pg: pg.cpp
	# build and execute
	g++ -O2 -std=c++17 pg.cpp SinglyLinkedList.cpp DoublyLinkedList.cpp && ./a.out
